name: Prebuild Binaries and Publish

on:
  push:
    branches:
      - main

jobs:
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-2019
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild --strip -t 18.0.0 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild --strip -t 18.0.0 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
